### ISSUE TITLE
REST - Webservice - JSON Api

### ISSUE THREAD

**Issue by JohneDoe** [goalgorilla/open_social#370]
Is there any Rest- Interface i can use to do some CRUD operations??

**Comment by ribel** [comment]
Hi @JohneDoe,
There is Drupal core module [RESTful Web Services](https://www.drupal.org/docs/8/core/modules/rest/overview) and contrib [REST UI](https://www.drupal.org/project/restui) module.

But on Open Social roadmap is implementing [JSON API](https://www.drupal.org/project/jsonapi) and [Simple OAuth](https://www.drupal.org/project/simple_oauth) contrib modules, which are part of Drupal and Open Social API First initiative, and are more flexible and powerful.
We are going to implement them by the end of June.

We would be to glad to hear what kind REST services you need in Open Social.
Let me know if my answer helps.

**Comment by JohneDoe** [comment]
Hi,

the Rest Interface got lost on your Roadmap.
https://www.drupal.org/node/2766871

Our main focus is to add, read and update Groups and Memberts to Groups.

PUT /GROUP
GET /GROUP
PUT /GROUPMEMBER
GET /GROUPMEMBER
DELETE /GROUPMEMBER
