### ISSUE TITLE
Social Tour Module

### ISSUE THREAD

**Issue by rosemeria** [goalgorilla/open_social#399]
The emphasis in onboarding should not be on getting new users to click/tap around and familiarize themselves with the interface, but on helping them achieve their goals using your app.

Open Social Tour - my text corrections and suggestions…

tour.tour.social_home.yml
    label: 'Welcome on the home page stream!' 
Correction=> *Welcome to the homepage stream!*
    body: 'This is the place to stay up to date with the latest activity for all topics, groups and events! You can also post messages here for your entire community to see.' 
Suggestion=> *Keep up to date with all topics, groups, and events. You can post messages publicly or to the community (logged-in users).*

tour.tour.social_profile.yml
    label: 'Welcome on your profile stream!'
Correction=> *Welcome to your user profile stream!*
    body: "Here other community members can leave messages for you! You can also post messages on your own profile, these messages will be shown on other community members' homepage."
Suggestion=> *Tell the community about yourself and why you have joined. Other community members can leave you messages. You can also post messages which will show on other members' homepage stream.*

tour.tour.social_group.yml
    label: 'Welcome on this group page!'
Correction=> *Welcome, this is a group page!*
    body: 'Here you can see all the activity in this group and join it.'
Suggestion=>  *Here you can see all group activity. Create or follow group topics. Signup and attend group events. Join an open group or request invitation to be a member of a private group.*

tour.tour.social_explore.yml
    body: 'Click here to explore all the content in the community'
Suggestion=> *Explore all that’s happening in the community.*

tour.tour.social_event_overview.yml
    body: 'Use this filter if you only want to see either upcoming or past events'
Suggestion=>  *Use filters to help find events you are looking for.*

tour.tour.social_topic_overview.yml
    body: 'Here you can filter content for topic types'
Suggestion=>  *Use filters to help find the topic you are looking for.*

tour.tour.social_group_overview.yml
    body: 'Use this button to create a new topic, or to start a new event or group'
Suggestion=> * Add a new topic, event or start a new group.*

tour.tour.social_user.yml
    body: 'Welcome [current-user:display-name]. You have successfully created a password. Welcome to Open Social! With this platform you can collaborate with like minded people within the community!'
Correction=> *Welcome [current-user:display-name]. You have successfully created a password. Welcome to Open Social! With this platform you can easily share and collaborate with members of your community!* (note - “like minded” is a meaningless expression; can change with any given topic discussion!)

This is just a quick attempt at the tour verbiage. Hope it is helpful and will inspire more suggestions. I will be running some user testing next week and can get more feedback.
Aloha, Rose

**Comment by jochemvn** [comment]
Hi @rosemeria,
Thanks a lot for your input. Someone from out marketing department is reviewing your input. We'll let you know ASAP which changes are going to be added to OS.
Thanks again!
Jochem

**Comment by jochemvn** [comment]
Hi @rosemeria , 
We've reviewed your changes and added some of them to a new story we're going to work on soon. We're making some architectural changes to the tour module as well. Reason for that is that the current implementation does not work (well) on mobile. 
When we work on those changes, the textual changes will be added too. 

Thanks again for your input.

Jochem
