### ISSUE TITLE
Unable to override page-hero-data.html.twig

### ISSUE THREAD

**Issue by d21d3q** [goalgorilla/open_social#489]
I have custom content type page and I would like to have custom header (without hero image). I copied `page-hero-data.html.twig` into my theme folder, but on page source (with debugging turned on) I can still see path to file socialbase folder. Moreover, there are no filename suggestions for `page_hero_data` theme hook.

**Comment by jochemvn** [comment]
Hi @d21d3q,
We don't use GH issue for support. Please read [this section](https://www.drupal.org/docs/8/distributions/open-social/about-open-social-support) on how to get support. I'm closing this issue.
Jochem
