### ISSUE TITLE
AEgir installation fails.

### ISSUE THREAD

**Issue by spoetnik** [goalgorilla/open_social#63]
I tried installing open_social using the aegir hosting platform.
The verification of the platform went good, but installing a site fails. (AEgir works with platforms (site distributions), and sites (a site is installed from an installation profile from a platform)

    Drush command terminated abnormally due to an unrecoverable error. Error: Call to a member function getPath() on a non-object in /var/aegir/platforms/open_social-8.x-1.x/core/includes/install.inc, line 943

An easy way to spin up an AEgir platform is using https://www.drupal.org/project/valkyrie

**Comment by spoetnik** [comment]
Solved.....

    drush dl composer_manager
    php modules/composer_manager/scripts/init.php

   composer drupal-update
   composer dump-autoload

**Comment by jaapjan** [comment]
Hi @spoetnik , 

nice find! Please note that composer_manager will become a deprecated module in the future.

Do you know if there is support for Composer-based installations in Aegir? This could be an interesting feature I guess https://github.com/goalgorilla/social_template This would allow you to use a template like this for example.

**Comment by spoetnik** [comment]
At the moment there is no way of using Aegir with a Composer install :-(

https://www.drupal.org/node/2736801
