### ISSUE TITLE
UX - Minor css problem with navbar responsive

### ISSUE THREAD

**Issue by rosemeria** [goalgorilla/open_social#65]
![navbar-issue](https://cloud.githubusercontent.com/assets/1322331/18463764/21ff04ec-7928-11e6-8f69-690b783b2432.png)

I think this will fix the navbar float issue I am experiencing in smaller screen size. Tested on chrome and Safari.

Fix float problem in  navbar.scss: 
// Style overrides:

.navbar .navbar-toggle {
  border: 0;
  border-radius: 0;
  color: white;
  font-weight: 500;
  padding: 8px 10px;
  height: 50px;
  min-width: 50px;
  margin: 0;
  **float: none;  /*remove float none*/**
}

And add float:
**.navbar-header { 
float: left;
}** 

![navbar-fixed](https://cloud.githubusercontent.com/assets/1322331/18464057/404da302-792a-11e6-8278-3f77897b928f.png)

--Rose

**Comment by MaikelGG** [comment]
@rosemeria Thank you for the heads up. I noticed it as well. We will change the order of the blocks, so the user menu will be put first in the DOM and then the main menu. This should fix the problem.
