### ISSUE TITLE
some questions after first installed

### ISSUE THREAD

**Issue by ChenZhaobin** [goalgorilla/open_social#658]
1.only "say something to the communities" can show in frontpage,no matter what I have done ,I can't post blog or event  to show in frontpage - stream page ,but sometimes it could be showed in explore page.
2. some configuration pages are blank ,is this normal? such as there is nothing in  " Activity settings" page.
3.how to add some other social login,such as wechat and QQ,I am in China ,maybe some resources I can't reach.
4.the login view is not friendly enough,it should have a register link in that view .

**Comment by ChenZhaobin** [comment]
when I publish an event,error shows that "An illegal choice has been detected. Please contact the site administrator."

**Comment by slowflyer** [comment]
Hi ChenZhaobin,
as you may have seen in previous issues, GH issues are not used for support. Please read [this section](https://www.drupal.org/docs/8/distributions/open-social/about-open-social-support) on how to get support.
