### ISSUE TITLE
event  visibility settings

### ISSUE THREAD

**Issue by ChenZhaobin** [goalgorilla/open_social#659]
1.how can I create an event in a group ,but it can be seen by not logged in users.
2.Why not just one  create  event page ,and in this page we can both config which group it belongs to or public

**Comment by ChenZhaobin** [comment]
why it only has two choice of visibility open and community when I create an event,Why not including group visibilty?

**Comment by jochemvn** [comment]
Hi @ChenZhaobin 
We don't use the github issue queue for support, but we use the drupal.org [issue queue](https://www.drupal.org/project/issues/social). Please create your issue there. I will close this one here.
kind regards,
Jochem
