### ISSUE TITLE
Error in composer

### ISSUE THREAD

**Issue by olariuromeo** [goalgorilla/open_social#682]
[RuntimeException]                                                                                           
  Failed to execute git clone --no-checkout 'git@github.com:scottjehl/Respond.git' '/var/www/vendor/bower-ass  
  et/respond' && cd '/var/www/vendor/bower-asset/respond' && git remote add composer 'git@github.com:scottjeh  
  l/Respond.git' && git fetch composer

**Comment by frankgraave** [comment]
Hi @olariuromeo 

We handle issues on drupal.org. You can create an issue [here](https://www.drupal.org/project/issues/social?categories=1). Also, when submitting an issue, try to provide some more information about your error.

Thanks, Frank.
