### ISSUE TITLE
"Add the hero styled image" fails when using custom content types and not following convention: "field_{$node->getType()}_image", or if you want to reuse an image field from another content type

### ISSUE THREAD

**Issue by g3r4** [goalgorilla/open_social#726]
If you extend and use a custom content type (not provided by Open Social) and happens to have a long name, the validation will fail because machine names can only be 26 characters long.
In order to at least have the possibility of having an image set, we need code that helps to load an image field as hero, as long as it has the word "image" on its field name and it is an image field.

I will add a pull request with this extra handling for your consideration

**Comment by jaapjan** [comment]
Hey @g3r4 Thanks for your contribution! I think this is a good idea. I've created an issue on drupal.org for this since we use that for issue tracking:

https://www.drupal.org/project/social/issues/2944419

I will continue there and in the pullrequest created and close this issue for now.
